services:
  db-dev:
    image: postgres:14.3
    restart: always
    ports:
      - '5438:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: ${CONTAINER_NAME}
    volumes:
      - ./postgres-dev:/var/lib/postgresql/data

  db-test:
    image: postgres:14.3
    restart: always
    ports:
      - '5437:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: ${CONTAINER_NAME}
    volumes:
      - ./postgres-test:/var/lib/postgresql/data
