services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '${PROJECT_LOCAL_PORT}:${PROJECT_CONTAINER_PORT}'
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PROJECT_LOCAL_PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
