services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - '5437:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: ScheduleDb
    volumes:
      - ./postgres:/var/lib/postgresql/data
    env_file: .env.development
