export { AppointmentLaboralHoursException } from './appointment-laboral-hours'
export { AppointmentPastDateException } from './appointment-past-date'
export { AppointmentNotFoundException } from './appointment-not-found'
export { AppointmentAlreadyExitsException } from './appointment-already-exists'
export { AppointmentLimitPerHourException } from './appointment-limit-per-hour'
