name: Continuous Integration for ScheduleApi

on:
  pull_request:
    branches: ['develop', 'main']

jobs:
  avoid-redundant-builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cancel previous redundant runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.7
        options: --privileged
    steps:
      - uses: actions/checkout@v4

      - name: Get Yarn cache directory path
        id: yarn-cache-dir
        run: |
          echo "cache-path=$(yarn cache dir)" >> $GITHUB_OUTPUT
          echo "Yarn cache directory path is $(yarn cache dir)"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
          cache: 'yarn'

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            **/.eslintcache
            ${{ steps.yarn-cache-dir.outputs.cache-path }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build Docker Images
        run: docker-compose -f docker-compose.test.yaml build

      - name: Start Test Environment
        run: docker-compose -f docker-compose.test.yaml up -d db-testing my-service-dev

      - name: Wait for Postgres to be ready
        run: |
          until docker-compose -f docker-compose.test.yaml exec db-testing pg_isready -U ${{ secrets.POSTGRES_USER_TEST }}; do
            sleep 1;
          done

      - name: Generate Prisma Client
        run: docker-compose -f docker-compose.test.yaml exec my-service-dev yarn prisma generate

      - name: Push Database Schema
        run: docker-compose -f docker-compose.test.yaml exec my-service-dev yarn prisma db push

      - name: Run Tests
        run: docker-compose -f docker-compose.test.yaml exec my-service-dev yarn test

      - name: Stop Test Environment
        run: docker-compose -f docker-compose.test.yaml down
