name: Continuous Integration for ScheduleApi

on:
  pull_request:
    branches: ['develop', 'main']

jobs:
  avoid-redundant-builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cancel previous redundant runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.7
        options: --privileged
    env:
      PORT: ${{ secrets.PORT }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
      DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
      PRISMA_LOG_LEVEL: ${{ secrets.PRISMA_LOG_LEVEL }}
      POSTGRES_USER_TEST: ${{ secrets.POSTGRES_USER_TEST }}
      POSTGRES_PASSWORD_TEST: ${{ secrets.POSTGRES_PASSWORD_TEST }}
      POSTGRES_DB_TEST: ${{ secrets.POSTGRES_DB_TEST }}

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Images
        run: docker-compose -f docker-compose.test.yaml build

      - name: Start Test Environment
        run: docker-compose -f docker-compose.test.yaml up -d db-testing my-service-dev

      - name: Wait for Postgres to be ready
        run: |
          until docker-compose -f docker-compose.test.yaml exec -T db-testing pg_isready -U ${{ secrets.POSTGRES_USER_TEST }}; do
            sleep 1;
          done

      - name: Run lint
        run: docker-compose -f docker-compose.test.yaml exec -T my-service-dev yarn lint

      - name: Push Database Schema
        run: docker-compose -f docker-compose.test.yaml exec -T my-service-dev yarn prisma db push

      - name: Run Tests
        run: docker-compose -f docker-compose.test.yaml exec -T my-service-dev yarn test

      - name: Stop Test Environment
        run: docker-compose -f docker-compose.test.yaml down
